"""
Counting DNA nucleotides.

Given: A DNA string s of length at most 1000.
Return: Four integers (seperated by spaces) counting the respective
number of times that the symbols A, C, G, and T occur in s.
"""

def count_dna_nucleotides(dna_string):
    D = {k:0 for k in ['A', 'C', 'G', 'T']}
    for nucleotide in dna_string:
        D[nucleotide] += 1
    return D

answer = count_dna_nucleotides('TAATAGGCACGTCCCATATTCTTGTCTATCGGTACGTTAATTGTGTACTCGGTTCCAGGTCCTTGAACAAATATTACAGGTTGATTGTGAAGACCCCAGCTACACCAATTCCCCTTGTCTGTGTGCTTAAATTCGGGGCTCTAATCAATTGAGCAAGGCGTGAGGTTAGCTATTGGTTGCCACGTACAATGCGAGGTGCGTTTGCATTATCTCGAAGTCGGATGATACTCCGTTATTGAAGACGCGTTCTGAAGAAGGTCCTAGGGTACAGGGCCTATGAAGGAGAATAGATGACCAGAATAAAGTGGAATATGCACTGATCTACACTTTCGGCGAGGTATTGTACCTAGATGCAGGCCACCTGTTAAGTCGTCGTAATAGCACCGCACTCAGGGTCGATACCCCTTTCAACAGCGATAGATGGGAAAATAATCTATATGAATGGCTGCTGTTGATTAACTATCTTAGCAATTCTGTGGCTTCGTCGTGGTGAGTAAGTCGACTGAATTCTTTAAGTTAGTGTAGGCGCAAGCCAGATCACTTAATACCACGCTCGTGTCTTGCTGGAATTTACTAGGAATTTACCCACCATTGAATGATTAAAATATTTGCATGGGCTTGGGCTTATTTATGGTCTGCCGACGAGAAGGACAACTCCGCAGCTACCCGAGTTATGCCAGCAGAAGAGTAGTTCTGATACCAGGCACGCACACCACACATACTAGATACATTTCTATCCTAATATATCGATCGCGGCAAGTCATCGACGGCGGCGCTCATAGGCGATGAACATATCTTTATAGGCTGGACTTTACGGCGTATCGATTGGCGAGTTTGAGGTTGAATCAATTAGATATGGCCGCTGCTCCGACATATTGCGAATGTCCCGAGGAGGGCGAGGACGGCGAGACCACACGCAACGGCGCCGTCACGTAATAGACCATCGACCACGGCGTAATTGACTGATGGTTTC')
print(' '.join([str(v) for k, v in answer.items()]))
